/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Browser.java
 *
 * Created on 24-01-2011, 13:20:18
 */

package failbrowser;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author Nyvang
 */
public class Browser extends javax.swing.JFrame {

    /** Creates new form Browser */
    public Browser() {
        initComponents();
        contentPage.setEditable(false);
        //add a hyperlink listener on the content pane to enable hyperlink clicking
        contentPage.addHyperlinkListener(
                new HyperlinkListener()
                {
                    public void hyperlinkUpdate(HyperlinkEvent event)
                    {
                        if(event.getEventType() == HyperlinkEvent.EventType.ACTIVATED)
                            {getPage(event.getURL().toString());}
                    }//end hyperlinkUpdate
                }//end hyperlinkListener

                );

    }//end constructor

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPage = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MeLikeBrowsing 1.0");

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(contentPage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        getPage(evt.getActionCommand());
    }//GEN-LAST:event_addressFieldActionPerformed

    /*
     * Assigns the page(location) to the contentpane
     *
     */
    private void getPage(String location)
    {
        //check if the URL contains http:// - else add it to the beginning
        if(!location.contains("http://"))
        {
            location = "http://" + location;
        }//end if
        try
        {
            contentPage.setPage(location);
            addressField.setText(location);
        }//end try
        catch (IOException ioe)
        {
            JOptionPane.showMessageDialog(this,"An error occoured while trying to read URL", "Bad URL", JOptionPane.ERROR_MESSAGE);
        }//end catch
    }//end method getPage



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JEditorPane contentPage;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
